const express = require("express");
const router = express.Router();
const userController = require("../controllers/userController");
const verifyToken = require("../middleware/verifyToken");
router.post("/register", userController.register);
router.post("/send-otp", userController.sendOtp);
router.post("/verify-otp", userController.verifyOtp);
router.post("/login", userController.login);
router.post("/getuser", verifyToken, userController.getUserById);
module.exports = router;
